services:
  sqlsrv:
    build: docker/sqlsrv2022
    ports:
      - ${EXMENT_DOCKER_SQLSRV_PORT-1433}:1433
    networks:
      - exment-network
    env_file: .env
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${EXMENT_DOCKER_SQLSRV_ROOT_PASSWORD}
      MSSQL_PID: ${EXMENT_DOCKER_SQLSRV_PID-Express}
      SQLSRV_COLLATION: Japanese_CI_AS
      # - SQLSRV_LCID: 1041

  sqlsrv-create-db:
    image: tsgkadot/mssql-tools
    command: |
      /home/wait-for-it.sh sqlsrv:1433 --timeout=30 --strict -- sqlcmd -S sqlsrv -U sa -P ${EXMENT_DOCKER_SQLSRV_ROOT_PASSWORD} -Q "CREATE DATABASE ${EXMENT_DOCKER_SQLSRV_DATABASE} COLLATE Japanese_CI_AS"
    volumes:
      - ./docker/mssql-tools:/home
    networks:
      - exment-network
    env_file: .env

networks:
  exment-network:
